
##
## STEP 1 - BUILD
##
FROM golang:1.21 AS build 
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bootstrap ./cmd/otel-jaeger

##
## STEP 2 - DEPLOY
##
FROM alpine:latest

WORKDIR /

COPY --from=build /bootstrap /bootstrap

RUN apk update && apk add curl

EXPOSE 8080

ENTRYPOINT ["/bootstrap"]